- name: Install graphing related utilities
  become: true
  hosts: graf
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: prometheus
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets: "{{ ansible_play_hosts | map('regex_replace', '(.+)', '\\1:9090') | list }}"
      - job_name: node_exporter
        metrics_path: /metrics
        static_configs:
          - targets: "{{ groups['all'] | map('regex_replace', '(.+)', '\\1:9100') | list }}"