- name: Setup prometheus + exporters + alerts
  become: true
  hosts: graf
  roles:
    - prometheus.prometheus.prometheus
    - prometheus.prometheus.blackbox_exporter
  tasks:
    - name: Download awesome-prometheus-alerts
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /etc/prometheus/rules/{{ (item | split('/'))[-2:] | join('_') | regex_replace('yml', 'rules') }}
        mode: 0640
        owner: prometheus
        group: prometheus
      loop:
        - https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/dist/rules/prometheus-self-monitoring/embedded-exporter.yml
        - https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/dist/rules/host-and-hardware/node-exporter.yml
        - https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/dist/rules/blackbox/blackbox-exporter.yml
        - https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/dist/rules/zfs/node-exporter.yml
      notify: Reload prometheus
- name: Setup grafana
  become: true
  hosts: graf
  roles:
    - grafana.grafana.grafana
  tags:
    - grafana
- name: Setup loki (taylors version)
  become: true
  hosts: graf
  roles:
    - loki
  tags:
    - loki